# Generated by Django 2.1.7 on 2019-08-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.IntegerField()),
                ('bus_direction', models.TextField()),
                ('bus_time', models.DurationField()),
            ],
        ),
    ]
