# Generated by Django 2.1.7 on 2019-08-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_time',
            field=models.TextField(),
        ),
    ]
