# Generated by Django 2.1.7 on 2019-08-29 03:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190827_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Engineering college', 'Engineering college'), ('Dentist college', 'Dentist college'), ('commerce college', 'commerce college')], max_length=52),
        ),
    ]
